import { NextResponse } from 'next/server'

export async function GET() {
  const data = {
    symbol: '513380.SS',
    latestSignal: {
      action: 'BUY' as const,
      asset: '恒生科技ETF龙头',
      price: 1.183,
      timestamp: '2024-12-06T10:30:00Z',
      reason: 'MA交叉买入 [MA5=1.100 > MA20=1.090]'
    },
    positionInfo: {
      initialCapital: 50000.00,
      currentValue: 80910.43,
      totalReturn: 61.82,
    },
    performanceMetrics: [
      { name: '年化收益率', value: '24.52%', description: '将总收益率转换为年化收益率' },
      { name: '最大回撤', value: '10.60%', description: '历史最大的亏损幅度' },
      { name: '夏普比率', value: '2.31', description: '每承受一单位总风险，会产生多少的超额报酬' },
      { name: 'Calmar比率', value: '2.31', description: '年化收益率与最大回撤的比值' },
      { name: '累计收益率', value: '61.82%', description: '从策略开始到现在的总收益率' },
      { name: '胜率', value: '65.2%', description: '盈利交易占总交易的比例' },
      { name: '平均盈利', value: '¥1,523.45', description: '每笔盈利交易的平均收益' },
      { name: '平均亏损', value: '¥-876.32', description: '每笔亏损交易的平均损失' },
      { name: '盈亏比', value: '1.74', description: '平均盈利与平均亏损的比值' },
      { name: '最大连续盈利次数', value: '8', description: '最多连续盈利的交易次数' },
      { name: '最大连续亏损次数', value: '3', description: '最多连续亏损的交易次数' },
    ],
    marketIndicators: [
      { name: 'RSI', value: '65.4', description: '相对强弱指标' },
      { name: 'MACD', value: '0.0023', description: '指数平滑移动平均线' },
      { name: 'Bollinger Bands', value: '上轨: 1.50, 下轨: 1.46', description: '布林带' },
      { name: 'ATR', value: '0.028', description: '平均真实波幅' },
      { name: '成交量', value: '1,234,567', description: '当日成交股数' },
      { name: '成交额', value: '¥1,460,292.56', description: '当日成交金额' },
      { name: '换手率', value: '2.34%', description: '成交量与流通股本的比率' },
      { name: '市盈率 (P/E)', value: '18.5', description: '每股市价与每股盈利的比率' },
      { name: '市净率 (P/B)', value: '2.3', description: '每股市价与每股净资产的比率' },
    ],
    riskMetrics: [
      { name: '波动率', value: '15.2%', description: '收益率的标准差' },
      { name: 'Beta系数', value: '1.2', description: '相对于大盘的波动程度' },
      { name: '信息比率', value: '0.75', description: '超额收益与跟踪误差的比值' },
      { name: '索提诺比率', value: '1.8', description: '考虑下行风险的风险调整后收益指标' },
      { name: 'VaR (95%置信度)', value: '¥2,345.67', description: '在正常市场条件下，某一金融资产或证券组合的最大可能损失' },
      { name: '最长回撤期', value: '45天', description: '从最大回撤开始到恢复所需的最长时间' },
      { name: '跟踪误差', value: '2.1%', description: '策略收益与基准收益差异的波动性' },
    ],
    recentTrades: [
      {
        date: '2024-11-08',
        action: 'SELL' as const,
        price: 1.183,
        quantity: 65138,
        value: 77058.25,
        pnl: 3567.54,
        totalValue: 80910.43,
        reason: '均线交叉卖出 [MA5=1.128 > MA20=1.120]',
      },
      {
        date: '2024-11-07',
        action: 'BUY' as const,
        price: 1.128,
        quantity: 65138,
        value: 73475.66,
        pnl: 0,
        totalValue: 77335.54,
        reason: 'MA交叉买入 [MA5=1.128 > MA20=1.120]',
      },
      {
        date: '2024-10-09',
        action: 'SELL' as const,
        price: 1.198,
        quantity: 62299,
        value: 74634.20,
        pnl: 20421.19,
        totalValue: 77342.89,
        reason: '止盈卖出 [ATR=0.028, 最高价=1.301, 止盈价=1.203]',
      },
      {
        date: '2024-10-01',
        action: 'BUY' as const,
        price: 1.105,
        quantity: 62299,
        value: 68840.45,
        pnl: 0,
        totalValue: 71549.23,
        reason: 'RSI超卖反弹 [RSI=28.5 < 30]',
      },
      {
        date: '2024-09-15',
        action: 'SELL' as const,
        price: 1.220,
        quantity: 58606,
        value: 71499.32,
        pnl: 15236.78,
        totalValue: 71499.32,
        reason: 'MACD死叉卖出 [MACD=-0.002 < Signal=-0.001]',
      },
    ],
    strategyParameters: [
      { name: 'symbol', value: '513380.SS' },
      { name: 'start_date', value: '2022-01-01 00:00:00' },
      { name: 'end_date', value: '2024-12-07 00:00:00' },
      { name: 'use_ma', value: 'True' },
      { name: 'ma_short', value: 5 },
      { name: 'ma_long', value: 20 },
      { name: 'use_atr', value: 'True' },
      { name: 'atr_period', value: 14 },
      { name: 'atr_multiplier', value: 2.0 },
      { name: 'use_rsi', value: 'True' },
      { name: 'rsi_period', value: 14 },
      { name: 'rsi_overbought', value: 70 },
      { name: 'rsi_oversold', value: 30 },
      { name: 'use_macd', value: 'True' },
      { name: 'macd_fast', value: 12 },
      { name: 'macd_slow', value: 26 },
      { name: 'macd_signal', value: 9 },
      { name: 'stop_loss', value: '5%' },
      { name: 'take_profit', value: '10%' },
    ],
  }

  return NextResponse.json(data)
}

